### ISSUE TITLE
Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by miladmeidanshahi** [onsip/SIP.js#634]
**Describe the bug**
after incoming call i get this error

**Environment Information**
sip.js ver 0.12.0
google chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
```
Transactions.js:435 Uncaught TypeError: Cannot read property 'debug' of undefined
    at a.timer_H (Transactions.js:435)
```

**Comment by egreenmachine** [comment]
Please provide a [gist](https://gist.github.com/) of full logs from SIP.js

**Comment by egreenmachine** [comment]
Never mind. We tracked this down and it will be fixed in the next release.

**Comment by egreenmachine** [comment]
Fixed 98a1271d5700be5703117b419c63368a9d7e13dd

**Comment by geilt** [comment]
Hello, Sorry to open this up. But Timer_L has the exact same issue it seems, missing the bind.

**Comment by timo-klarshift** [comment]
I think still Bug is still present, please see my comment in the Commit https://github.com/onsip/SIP.js/commit/98a1271d5700be5703117b419c63368a9d7e13dd#diff-ef9ade42e4a5eaa513b3d74c3f4f8c0c

![2019-04-18-114204_977x353_scrot](https://user-images.githubusercontent.com/1379383/56352383-7163c800-61cf-11e9-8b8e-55f46561b13d.png)
![2019-04-18-114321_543x165_scrot](https://user-images.githubusercontent.com/1379383/56352385-7163c800-61cf-11e9-91b1-a8b9be0f8312.png)
