### ISSUE TITLE
peerConnectionOptions of undefined

### ISSUE THREAD

**Issue by Skramewell** [onsip/SIP.js#648]
When i answer a call with `window.UA.session.accept()`, i get this error:

`Uncaught (in promise) TypeError: Cannot read property 'peerConnectionOptions' of undefined
    at SessionDescriptionHandler.getDescription (SessionDescriptionHandler.js?c864:129)
    at eval (Session.js?79eb:1000)`

This is my sip configuration:

` 
sessionDescriptionHandlerFactoryOptions: {
      constraints: {
        audio: true,
        video: false
      },
      peerConnectionOptions: {
        iceCheckingTimeout: 750
      }
},
`

**Comment by james-criscuolo** [comment]
Can you build with `master` and retest. This looks to have been fixed with https://github.com/onsip/SIP.js/commit/20cd898aeaa3392e028129ebde2c16d22865122d

**Comment by Skramewell** [comment]
Sorry, but I have installed latest version of sip.js `"sip.js": "^0.13.2"` and the problem persist.
Do you have any other suggestion?

**Comment by james-criscuolo** [comment]
Master is not yet released, so you'd be testing something you do not have yet.

**Comment by james-criscuolo** [comment]
We're reasonably confident this was fixed with the commit I was referring to, which is now released in 0.13.3. I'm resolving, but let us know if 0.13.3 does not fix this.

**Comment by Skramewell** [comment]
I have made a test and its now fixed on `master ` and  version `0.13.3` also. Thanks!
