### ISSUE TITLE
Can't answer invitation/bad user agent delegate?

### ISSUE THREAD

**Issue by ksitko** [onsip/SIP.js#723]
**Describe the bug**
I'm unable to accept an incoming call in the new API. When the other user calls the account which my user agent is registered to I hear a ringing sound, but that's about it. My UserAgent delegate statement follows precisely the example presented in [the new api docs](https://github.com/onsip/SIP.js/tree/master/docs) but can't even get a console output on invitation.

**To Reproduce (if possible)**
```javascript
    this.userAgent.delegate = {
      onInvite(invitation: Invitation): void {
        console.log("Invitation!"); //This does not print
        // An Invitation is a Session
        const incomingSession: Session = invitation;
        // Setup incoming session delegate
        incomingSession.delegate = {
          // Handle incoming REFER request.
          onRefer(referral: Referral): void {
            // ...
          }
        };
        incomingSession.stateChange.on((newState: SessionState) => {
          switch (newState) {
            case SessionState.Establishing:
              // Session is establishing.
              break;
            case SessionState.Established:
              // Session has been established.
              break;
            case SessionState.Terminated:
              // Session has terminated.
              break;
            default:
              break;
          }
        });
      }
    };

```
Am I doing something wrong here?

**Comment by egreenmachine** [comment]
How is your user agent constructed?

**Comment by ksitko** [comment]
```javascript
    this.state = {
      uri: new URI("sip", "k", "alzai.onsip.com"),
      server: "wss://edge.sip.onsip.com",
      username: "k",
      password: "",
      target: "test@alzai.onsip.com",
      connected: false,
      ringing: false,
      inCall: false
    };

...
  initializeUA = () => {
    const { uri, server, username, password } = this.state;
    const userAgentOptions: UserAgentOptions = {
      uri: uri,
      transportOptions: {
        wsServers: [server]
      },
      authorizationUsername: username,
      authorizationPassword: password,
      sessionDescriptionHandlerFactory:
        SessionDescriptionHandler.defaultFactory
      };
    this.userAgent = new UserAgent(userAgentOptions);
```
I seem to have broken something as now my User is no longer showing up as registered in my onsip admin page, however for whatever reason I am still able to make a call despite not showing up. Additional logs if helpful:
```
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | Configuration:
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · allowLegacyNotifications: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · allowOutOfDialogRefers: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · authorizationPassword: NOT SHOWN
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · authorizationUsername: "k"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · autoStart: true
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · autoStop: true
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · delegate: {}
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · displayName: ""
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · forceRport: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · hackIpInContact: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · hackViaTcp: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · hackWssInTransport: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · logBuiltinEnabled: true
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · logConfiguration: true
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · logConnector: undefined
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · logLevel: "log"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · noAnswerTimeout: 60
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · sessionDescriptionHandlerFactory: function (session, options) {
      var logger = session instanceof session_1.Session ? session.userAgent.getLogger("sip.sessionDescriptionHandler", session.id) : session.ua.getLogger("sip.invitecontext.sessionDescriptionHandler", session.id);
      var observer = new SessionDescriptionHandlerObserver_1.SessionDescriptionHandlerObserver(session, options);
      return new SessionDescriptionHandler(logger, observer, options);
    }
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {}
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · sipExtension100rel: "Unsupported"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · sipExtensionReplaces: "Unsupported"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · sipExtensionExtraSupported: []
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · sipjsId: "088t4"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · transportConstructor: Transport
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · transportOptions: {"wsServers":["wss://edge.sip.onsip.com"]}
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · uri: sip:k@alzai.onsip.com
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · usePreloadedRoute: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · userAgentString: "SIP.js/0.15.3"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | · viaHost: "9imv92dcoosu.invalid"
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | configuration parameters after validation:
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · wsServers: [{"wsUri":"wss://edge.sip.onsip.com","sipUri":"<sip:edge.sip.onsip.com;transport=ws;lr>","weight":0,"isError":false,"scheme":"WSS"}]
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · connectionTimeout: 5
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · maxReconnectionAttempts: 3
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · reconnectionTimeout: 4
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · keepAliveInterval: 0
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · keepAliveDebounce: 10
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | · traceSip: false
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | user requested startup...
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | connecting to WebSocket wss://edge.sip.onsip.com
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | user requested startup...
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.UserAgent | UA is in STARTING status, not opening new connection
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | Attempting to transition status from 0 to 1
Tue Jul 30 2019 14:01:52 GMT-0400 (EDT) | sip.transport | WebSocket wss://edge.sip.onsip.com connected

```

**Comment by egreenmachine** [comment]
Everything looks correct. Please enable `traceSip` and provide full logs showing the issue.

**Comment by ksitko** [comment]
Okay, so I think I know why I was getting ringing, I was checking something with the old API and it successfully registered the old api user agent. When I was calling the user it was still under the not yet expired registration of the old API. Looking at my onsip admin panel I can see the call from the new API user agent even though it was not registered... I don't understand how that is happening. Here is the full logs of a call and hangup from the user which according to my onsip admin panel is not registered. I am not hearing any audio on either end in this call.
```
CallKeep Start
CallKeep Complete
URI {
  "headers": Object {},
  "normal": Object {
    "host": "alzai.onsip.com",
    "port": 5060,
    "scheme": "sip",
    "user": "k",
  },
  "parameters": Object {},
  "raw": Object {
    "host": "alzai.onsip.com",
    "port": 5060,
    "scheme": "sip",
    "user": "k",
  },
}
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | Configuration:
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · allowLegacyNotifications: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · allowOutOfDialogRefers: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · authorizationPassword: NOT SHOWN
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · authorizationUsername: "k"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · autoStart: true
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · autoStop: true
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · delegate: {}
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · displayName: ""
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · forceRport: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · hackIpInContact: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · hackViaTcp: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · hackWssInTransport: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · logBuiltinEnabled: true
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · logConfiguration: true
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · logConnector: undefined
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · logLevel: "log"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · noAnswerTimeout: 60
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · sessionDescriptionHandlerFactory: function (session, options) {
      var logger = session instanceof session_1.Session ? session.userAgent.getLogger("sip.sessionDescriptionHandler", session.id) : session.ua.getLogger("sip.invitecontext.sessionDescriptionHandler", session.id);
      var observer = new SessionDescriptionHandlerObserver_1.SessionDescriptionHandlerObserver(session, options);
      return new SessionDescriptionHandler(logger, observer, options);
    }
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {}
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · sipExtension100rel: "Unsupported"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · sipExtensionReplaces: "Unsupported"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · sipExtensionExtraSupported: []
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · sipjsId: "jlohb"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · transportConstructor: Transport
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · transportOptions: {"wsServers":["wss://edge.sip.onsip.com"],"traceSip":true}
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · uri: sip:k@alzai.onsip.com:5060
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · usePreloadedRoute: false
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · userAgentString: "SIP.js/0.15.3"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | · viaHost: "7ujjh78qs31p.invalid"
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | configuration parameters after validation:
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · wsServers: [{"wsUri":"wss://edge.sip.onsip.com","sipUri":"<sip:edge.sip.onsip.com;transport=ws;lr>","weight":0,"isError":false,"scheme":"WSS"}]
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · connectionTimeout: 5
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · maxReconnectionAttempts: 3
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · reconnectionTimeout: 4
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · keepAliveInterval: 0
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · keepAliveDebounce: 10
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | · traceSip: true
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | user requested startup...
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | connecting to WebSocket wss://edge.sip.onsip.com
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | user requested startup...
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.UserAgent | UA is in STARTING status, not opening new connection
UA Setup Done
Running application on iPhone X.
Storage content: 0a34fd885e1f00b75fcca619e3d84fe49b367414e506c10edaade14c275cfe96
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | Attempting to transition status from 0 to 1
Tue Jul 30 2019 15:27:57 GMT-0400 (EDT) | sip.transport | WebSocket wss://edge.sip.onsip.com connected
Call Device
Make Call
Invite Options
Inviter
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.inviter | Inviter.invite
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {}
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | initPeerConnection
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | New peer connection created
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | acquiring local media
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | acquired local media streams
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | createOffer
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | resetIceGatheringComplete
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | Setting local sdp.
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | sdp is v=0
o=- 8241945004634549173 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 9B70520E-27B9-41EF-AA4C-4A6F8276ACC2
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:PKyv
a=ice-pwd:EtEbDzQPMLcfnnDHIne1aDyF
a=ice-options:trickle renomination
a=fingerprint:sha-256 93:57:33:0D:2C:19:15:0E:99:59:F5:74:25:AA:3A:9C:A0:52:95:92:BC:62:CD:84:1A:59:70:0D:70:3D:F9:24
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2883117875 cname:Ja8Y6MFzuDsgHL2U
a=ssrc:2883117875 msid:9B70520E-27B9-41EF-AA4C-4A6F8276ACC2 1ED66AD7-6B54-493B-873D-A09EF0D2F436
a=ssrc:2883117875 mslabel:9B70520E-27B9-41EF-AA4C-4A6F8276ACC2
a=ssrc:2883117875 label:1ED66AD7-6B54-493B-873D-A09EF0D2F436
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:PKyv
a=ice-pwd:EtEbDzQPMLcfnnDHIne1aDyF
a=ice-options:trickle renomination
a=fingerprint:sha-256 93:57:33:0D:2C:19:15:0E:99:59:F5:74:25:AA:3A:9C:A0:52:95:92:BC:62:CD:84:1A:59:70:0D:70:3D:F9:24
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=125
a=rtpmap:124 ulpfec/90000

Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | waitForIceGatheringComplete
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | ICE is not complete. Returning promise
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | RTCIceGatheringState changed: gathering
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | ICE candidate received: candidate:1019731727 1 udp 2122260223 192.168.1.104 54177 typ host generation 0 ufrag PKyv network-id 1 network-cost 10
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | ICE candidate received: candidate:3180321211 1 udp 1686052607 73.160.218.187 54177 typ srflx raddr 192.168.1.104 rport 54177 generation 0 ufrag PKyv network-id 1 network-cost 10
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | ICE candidate received: candidate:1917068287 1 tcp 1518280447 192.168.1.104 56657 typ host tcptype passive generation 0 ufrag PKyv network-id 1 network-cost 10
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | ICE candidate gathering complete
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.sessionDescriptionHandler | RTCIceGatheringState changed: complete
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.inviter | Session jlohb75tv71unchced529fk94jku73 transitioned to state Establishing
Ringing
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.transport | sending WebSocket message:

INVITE sip:test@alzai.onsip.com SIP/2.0
Via: SIP/2.0/WSS 7ujjh78qs31p.invalid;branch=z9hG4bK1949304
To: <sip:test@alzai.onsip.com>
From: <sip:k@alzai.onsip.com:5060>;tag=9fk94jku73
CSeq: 1 INVITE
Call-ID: jlohb75tv71unchced52
Max-Forwards: 70
Contact: <sip:3lglmltf@7ujjh78qs31p.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: SIP.js/0.15.3
Content-Type: application/sdp
Content-Length: 3539

v=0
o=- 8241945004634549173 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 9B70520E-27B9-41EF-AA4C-4A6F8276ACC2
m=audio 54177 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 73.160.218.187
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1019731727 1 udp 2122260223 192.168.1.104 54177 typ host generation 0 network-id 1 network-cost 10
a=candidate:3180321211 1 udp 1686052607 73.160.218.187 54177 typ srflx raddr 192.168.1.104 rport 54177 generation 0 network-id 1 network-cost 10
a=candidate:1917068287 1 tcp 1518280447 192.168.1.104 56657 typ host tcptype passive generation 0 network-id 1 network-cost 10
a=ice-ufrag:PKyv
a=ice-pwd:EtEbDzQPMLcfnnDHIne1aDyF
a=ice-options:trickle renomination
a=fingerprint:sha-256 93:57:33:0D:2C:19:15:0E:99:59:F5:74:25:AA:3A:9C:A0:52:95:92:BC:62:CD:84:1A:59:70:0D:70:3D:F9:24
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2883117875 cname:Ja8Y6MFzuDsgHL2U
a=ssrc:2883117875 msid:9B70520E-27B9-41EF-AA4C-4A6F8276ACC2 1ED66AD7-6B54-493B-873D-A09EF0D2F436
a=ssrc:2883117875 mslabel:9B70520E-27B9-41EF-AA4C-4A6F8276ACC2
a=ssrc:2883117875 label:1ED66AD7-6B54-493B-873D-A09EF0D2F436
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:PKyv
a=ice-pwd:EtEbDzQPMLcfnnDHIne1aDyF
a=ice-options:trickle renomination
a=fingerprint:sha-256 93:57:33:0D:2C:19:15:0E:99:59:F5:74:25:AA:3A:9C:A0:52:95:92:BC:62:CD:84:1A:59:70:0D:70:3D:F9:24
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=125
a=rtpmap:124 ulpfec/90000


Successfully sent INVITE
1a400994-acfd-45df-adab-aa59c033e572
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.transport | received WebSocket text message:

SIP/2.0 100 Giving a try
Via: SIP/2.0/WSS 7ujjh78qs31p.invalid;received=73.160.218.187;rport=56139;branch=z9hG4bK1949304
To: <sip:test@alzai.onsip.com>
From: <sip:k@alzai.onsip.com:5060>;tag=9fk94jku73
CSeq: 1 INVITE
Call-ID: jlohb75tv71unchced52
Server: OpenSIPS (2.4.5 (x86_64/linux))
Content-Length: 0



Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.inviter | Inviter.onTrying
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Record-Route: <sip:199.7.173.180:443;transport=wss;r2=on;lr;ftag=9fk94jku73>
Record-Route: <sip:199.7.173.180;r2=on;lr;ftag=9fk94jku73>
Record-Route: <sip:199.7.173.100;lr;ftag=9fk94jku73;did=686.fc8a9ac7;ns=1;pr=3>
Record-Route: <sip:199.7.173.100;lr;ftag=9fk94jku73;nc=1;did=686.ec8a9ac7>
Record-Route: <sip:199.7.173.180;r2=on;lr;ftag=9fk94jku73>
Record-Route: <sip:199.7.173.180:443;transport=wss;r2=on;lr;ftag=9fk94jku73>
Via: SIP/2.0/WSS 7ujjh78qs31p.invalid;rport=56139;received=73.160.218.187;branch=z9hG4bK1949304
To: <sip:test@alzai.onsip.com>;tag=8g6ot28lab
From: <sip:k@alzai.onsip.com:5060>;tag=9fk94jku73
Call-ID: jlohb75tv71unchced52
CSeq: 1 INVITE
Contact: <sip:kmng51np*73.160.218.187!58286_n@199.7.173.100;transport=ws;gr>
Supported: outbound
User-Agent: SIP.js/0.13.8
Content-Length: 0
P-NS: 1



Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.invite-dialog | INVITE dialog jlohb75tv71unchced529fk94jku738g6ot28lab constructed
Tue Jul 30 2019 15:28:05 GMT-0400 (EDT) | sip.inviter | Inviter.onProgress
]
```

**Comment by egreenmachine** [comment]
You are not registered. Under the new API you need to explicitly register. This is in the guide. You are able to make outbound calls without registering. 

This is not a SIP.js bug, so I am going to close this issue.

**Comment by ksitko** [comment]
My mistake, I hadn't realized that was explicitly required now. I'm getting an error now though: `sip.user-agent-client | Unspecified transport error` 
My registerer looks as follows:
```javascript
    this.userAgent.start();
    const registererOptions: RegistererOptions = {};
    this.registerer = new Registerer(this.userAgent, registererOptions);
    this.registerer.stateChange.on(newState => {
      switch (newState) {
        case RegistererState.Registered:
          console.log("Registered");
          break;
        case RegistererState.Unregistered:
          console.log("Unregistered");
          break;
      }
    });
    this.registerer
      .register()
      .then(request => {
        console.log("Successfully sent REGISTER");
        console.log("REGISTER request = " + request);
      })
      .catch(error => {
        console.log("Failed to send REGISTER");
      });

```
```
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | configuration parameters for RegisterContext after validation:
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | · expires: 600
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | · extraContactHeaderParams: []
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | · instanceId: undefined
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | · params: {"toUri":{"parameters":{},"headers":{},"raw":{"scheme":"sip","user":"k","host":"alzai.onsip.com","port":5060},"normal":{"scheme":"sip","user":"k","host":"alzai.onsip.com","port":5060}},"toDisplayName":"","callId":"eqjl0su8k9ccs0j60r85bl","cseq":4767}
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | · regId: undefined
Tue Jul 30 2019 16:00:50 GMT-0400 (EDT) | sip.registercontext | · registrar: {"parameters":{},"headers":{},"raw":{"scheme":"sip","host":"alzai.onsip.com","port":5060},"normal":{"scheme":"sip","host":"alzai.onsip.com","port":5060}}
Successfully sent REGISTER
REGISTER request = undefined
Tue Jul 30 2019 16:00:51 GMT-0400 (EDT) | sip.transport | Attempting to transition status from 0 to 1
Tue Jul 30 2019 16:00:51 GMT-0400 (EDT) | sip.transport | WebSocket wss://edge.sip.onsip.com connected
```

**Comment by Nitrino** [comment]
I confronted with the same error. 
@ksitko You are fixed `Unspecified transport error` ?

**Comment by Nitrino** [comment]
This happens when I try to make a register.
```javascript
const uri = UserAgent.makeURI("sip:alice@localhost");
const userAgentOptions: UserAgentOptions = {
  uri: uri,
  authorizationUsername: "user",
  authorizationPassword: "password",
  transportOptions: {
    wsServers: [
      { wsUri: "ws://localhost:4000/sip/websocket" }
    ]
  },

};

const userAgent = new UserAgent(userAgentOptions);

/*
 * Start the user agent
 */
userAgent.start().then(() => {
  /*
   * Register the user agent
   */
  const registererOptions: RegistererOptions = {};
  const registerer = new Registerer(userAgent, registererOptions);
  registerer.register();
});

```

**Comment by ksitko** [comment]
I have not resolved this issue. I have since gone back to the previous version of the API for the time being.
